### ISSUE TITLE
Why i am getting Rest client error

### ISSUE THREAD

**Issue by Villonava** [alexdlaird/finicity-client#18]
com.github.alexdlaird.component.rest.RestClient$RestClientException: Rest client error
	at com.github.alexdlaird.component.rest.DefaultRestClient.executePost(DefaultRestClient.java:144)
	at com.github.alexdlaird.operation.DefaultPartnerOperations.authentication(DefaultPartnerOperations.java:75)
	at com.github.alexdlaird.DefaultFinicityClient.<init>(DefaultFinicityClient.java:132)
	at com.github.alexdlaird.DefaultFinicityClient.getInstance(DefaultFinicityClient.java:163)

**Comment by alexdlaird** [comment]
I should add some logging to improve this, but short of that, drop a breakpoint there and see what the authentication failure is. The likeliest scenario is that you'll need to take that message and reach out to Finicity, as it can take a bit of setting up to let your network or VPN (which, if I recall, needs a static IP) approved to talk to their API.
